FROM node:22-alpine

WORKDIR  /app


COPY package.json pnpm-lock.yaml ./

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install --frozen-lockfile 


COPY . .


EXPOSE 8000


CMD ["sh", "-c", "pnpm install --frozen-lockfile && pnpm run dev"]
